AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a VPC with public and private subnets in Mumbai

Parameters:
  CidrBlock:
    Description: CIDR block for the VPC (e.g., 10.0.0.0/16)
    Type: String
  PublicSubnet1CidrBlock:
    Description: CIDR block for the public subnet in Availability Zone 1 (e.g., 10.0.1.0/24)
    Type: String
  PublicSubnet2CidrBlock:
    Description: CIDR block for the public subnet in Availability Zone 2 (e.g., 10.0.2.0/24)
    Type: String
  PrivateSubnet1CidrBlock:
    Description: CIDR block for the private subnet in Availability Zone 1 (e.g., 10.0.10.0/24)
    Type: String
  PrivateSubnet2CidrBlock:
    Description: CIDR block for the private subnet in Availability Zone 2 (e.g., 10.0.20.0/24)
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC-Mumbai

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MyInternetGateway-Mumbai

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet1CidrBlock
      AvailabilityZone: "ap-south-1a" # Mumbai Zone 1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet1-Mumbai

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet2CidrBlock
      AvailabilityZone: "ap-south-1b" # Mumbai Zone 1b
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet2-Mumbai

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet1CidrBlock
      AvailabilityZone: "ap-south-1a" # Mumbai Zone 1a
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PrivateSubnet1-Mumbai

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet2CidrBlock
      AvailabilityZone: "ap-south-1b" # Mumbai Zone 1b
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PrivateSubnet2-Mumbai

Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref VPC
  PublicSubnet1Id:
    Description: Public Subnet 1 ID
    Value: !Ref PublicSubnet1
  PublicSubnet2Id:
    Description: Public Subnet 2 ID
    Value: !Ref PublicSubnet2
  PrivateSubnet1Id:
    Description: Private Subnet 1 ID
    Value: !Ref PrivateSubnet1
  PrivateSubnet2Id:
    Description: Private Subnet 2 ID
    Value: !Ref PrivateSubnet2
